# -*- coding: utf-8 -*-
"""Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2j_uqIOPc4V56KW2OBs56i5JyrkgA5v
"""

pip install pandas numpy scikit-learn

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

print(train.head())

train['Age'] = train['Age'].fillna(train['Age'].median())
train['Fare'] = train['Fare'].fillna(train['Fare'].median())
train['Embarked'] = train['Embarked'].fillna(train['Embarked'].mode()[0])

test['Age'] = test['Age'].fillna(test['Age'].median())
test['Fare'] = test['Fare'].fillna(test['Fare'].median())
test['Embarked'] = test['Embarked'].fillna(test['Embarked'].mode()[0])

train['Sex'] = train['Sex'].map({'male': 0, 'female': 1})
train['Embarked'] = train['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

test['Sex'] = test['Sex'].map({'male': 0, 'female': 1})
test['Embarked'] = test['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']
target = 'Survived'

X = train[features]
y = train[target]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

print("Model trained!")

val_preds = model.predict(X_val)

mse = mean_squared_error(y_val, val_preds)
r2 = r2_score(y_val, val_preds)

val_preds_binary = (val_preds >= 0.5).astype(int)
acc = accuracy_score(y_val, val_preds_binary)

print("MSE:", mse)
print("R2 Score:", r2)
print("Accuracy:", acc)

X_test = test[features]
test_preds = model.predict(X_test)
test_preds_binary = (test_preds >= 0.5).astype(int)

output = pd.DataFrame({
    'PassengerId': test['PassengerId'],
    'Survived_Predicted': test_preds_binary
})

output.to_csv('predictions.csv', index=False)
print(output.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(x='Sex', hue='Survived', data=train)
plt.xticks([0,1], ['Male', 'Female'])
plt.title('Survival Count by Gender')
plt.show()